CREATE TABLE CYCLES (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_PARENT INT,
	IS_CATHEDRA BIT NOT NULL DEFAULT 0,
    NAME_UK VARCHAR(255) NOT NULL,
	NAME_EN VARCHAR(255),
    NAME_RU VARCHAR(255),
    IS_OLD BIT NOT NULL DEFAULT 0,
    CHANGED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_PARENT) REFERENCES CYCLES(ID)
);
CREATE TABLE SEMESTERS
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME_UK VARCHAR(255) NOT NULL,
    NAME_EN VARCHAR(255),
    NAME_RU VARCHAR(255)
);
CREATE TABLE DISCIPLINES
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME_UK VARCHAR(255) NOT NULL,
    NAME_EN VARCHAR(255),
    NAME_RU VARCHAR(255),
    SHORT_NAME_UK VARCHAR(255) NOT NULL,
    SHORT_NAME_EN VARCHAR(255),
    SHORT_NAME_RU VARCHAR(255),
	IS_OLD BIT NOT NULL DEFAULT 0,
	CHANGED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE SYLLABI
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_DISCIPLINE INT NOT NULL,
    SYLLABUS_UK MEDIUMTEXT,
    SYLLABUS_EN MEDIUMTEXT,
    SYLLABUS_RU MEDIUMTEXT,
	IS_OLD BIT NOT NULL DEFAULT 0,
	CHANGED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_DISCIPLINE) REFERENCES DISCIPLINES(ID)
);
CREATE TABLE FORMS
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME_UK VARCHAR(255) NOT NULL,
    NAME_EN VARCHAR(255),    
    NAME_RU VARCHAR(255)
);
CREATE TABLE LEVELS
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME_UK VARCHAR(255) NOT NULL,
    NAME_EN VARCHAR(255),    
    NAME_RU VARCHAR(255)
);
CREATE TABLE CATHEDRAS
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME_UK VARCHAR(255) NOT NULL,
    NAME_EN VARCHAR(255),
    NAME_RU VARCHAR(255),
	SHORT_NAME_UK VARCHAR(255) NOT NULL,
    SHORT_NAME_EN VARCHAR(255),
    SHORT_NAME_RU VARCHAR(255)
);
CREATE TABLE SPECIALITIES
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME_UK VARCHAR(255) NOT NULL,
    NAME_EN VARCHAR(255),    
    NAME_RU VARCHAR(255)
);
CREATE TABLE TEACHERS
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME_UK VARCHAR(255) NOT NULL,
    NAME_EN VARCHAR(255),
    NAME_RU VARCHAR(255),
    FIRST_NAME_UK VARCHAR(100) NOT NULL,
    FIRST_NAME_EN VARCHAR(100),
    FIRST_NAME_RU VARCHAR(100),
    MIDDLE_NAME_UK VARCHAR(100),
    MIDDLE_NAME_EN VARCHAR(100),	
    MIDDLE_NAME_RU VARCHAR(100),
    LAST_NAME_UK VARCHAR(100) NOT NULL,
    LAST_NAME_EN VARCHAR(100),	
    LAST_NAME_RU VARCHAR(100),
    IS_OLD BIT NOT NULL DEFAULT 0,
    CHANGED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE YEARS
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
	IS_CURRENT BIT NOT NULL DEFAULT 0,
    IS_OLD BIT NOT NULL DEFAULT 0,
    CHANGED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE CURRICULUMS
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_CYCLE_GENERAL INT NOT NULL,
	ID_CYCLE_CUSTOM INT,
	ID_DISCIPLINE INT NOT NULL,
	ID_SPECIALITY INT NOT NULL,
	ID_LEVEL INT NOT NULL,
	ID_FORM INT NOT NULL,
	ID_SEMESTER INT NOT NULL,
	ID_TEACHER_LECTURE INT,
	ID_TEACHER_PRACTICE INT,
	ID_TEACHER_LABORATORY INT,
	ID_YEAR INT NOT NULL,
	ID_CATHEDRA INT NOT NULL,
	IS_OLD BIT NOT NULL DEFAULT 0,
	CHANGED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CYCLE_GENERAL) REFERENCES CYCLES(ID),
    FOREIGN KEY (ID_CYCLE_CUSTOM) REFERENCES CYCLES(ID),
    FOREIGN KEY (ID_DISCIPLINE) REFERENCES DISCIPLINES(ID),
    FOREIGN KEY (ID_SPECIALITY) REFERENCES SPECIALITIES(ID),
    FOREIGN KEY (ID_LEVEL) REFERENCES LEVELS(ID),
    FOREIGN KEY (ID_FORM) REFERENCES FORMS(ID),
    FOREIGN KEY (ID_SEMESTER) REFERENCES SEMESTERS(ID),
    FOREIGN KEY (ID_TEACHER_LECTURE) REFERENCES TEACHERS(ID),
    FOREIGN KEY (ID_TEACHER_PRACTICE) REFERENCES TEACHERS(ID),
    FOREIGN KEY (ID_TEACHER_LABORATORY) REFERENCES TEACHERS(ID),
    FOREIGN KEY (ID_YEAR) REFERENCES YEARS(ID),
    FOREIGN KEY (ID_CATHEDRA) REFERENCES CATHEDRAS(ID)
);
CREATE TABLE CURRICULUM_LINKS
(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_CURRICULUM_1 INT NOT NULL,
	ID_CURRICULUM_2 INT NOT NULL,
    IS_OLD BIT NOT NULL DEFAULT 0,
    CHANGED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_ID_CURRICULUM_1 FOREIGN KEY (ID_CURRICULUM_1) REFERENCES CURRICULUMS(ID),
    CONSTRAINT FK_ID_CURRICULUM_2 FOREIGN KEY (ID_CURRICULUM_2) REFERENCES CURRICULUMS(ID)
);